### ISSUE TITLE
CNN Accuracy Not Improving

### ISSUE THREAD

**Issue by ialsjbn** [blackmarble-2018/building-detection#2]
Hi,

Thank you for the very clear framework for building detection!

I was running your code, and for the most part, it seems like everything is working. However, when I start training the CNN model, the accuracy doesn't increase. It stays at around 0.6 for all epochs, as seen below (I tried only running 2 epochs as 10 epochs never finished running):

<img width="640" alt="image" src="https://user-images.githubusercontent.com/43555779/52728101-8623a580-2f6b-11e9-8799-8fb0510d4b6d.png">

To figure out what's going on, I tried outputting the results, and it seems like the image and the labels are mixed up. In images where there are no buildings, the actual label says there are buildings. And vice versa. Examples are seen below:

<img width="281" alt="image" src="https://user-images.githubusercontent.com/43555779/52728246-c125d900-2f6b-11e9-9175-572ea1868be0.png">

Is there something else I should be doing? Is there some specific way I should be organizing the files before running the model?

Thanks

**Comment by willgeary** [comment]
Sorry @ialsjbn but I don't have time to help troubleshoot problems related to this code. I can only direct you to the jupyter notebook for guidance. Please make sure you are running every cell exactly as they are.
